package services

import (
	"bytes"
	"fmt"
	"html/template"
	"time"

	"penego/models"
)

const reportHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Penego Report #{{.ID}}</title>
<style>
body{font-family:Georgia,serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}
h1{border-bottom:2px solid #333}
.meta{color:#555;margin-bottom:1.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0}
th,td{border:1px solid #ccc;padding:.4rem .6rem;text-align:left;font-size:.95rem}
th{background:#f0f0f0}
.alive{color:#0a7}
.dead{color:#a33}
.sev-high{color:#a00;font-weight:bold}
.sev-medium{color:#a60}
.sev-low{color:#06a}
@media print{body{margin:0}}
</style>
</head>
<body>
<h1>Penego Scan Report #{{.ID}}</h1>
<div class="meta">
<div><strong>Type:</strong> {{.ScanType}}</div>
<div><strong>Target:</strong> {{.Target}}</div>
<div><strong>Ports / Mode:</strong> {{.PortsScanned}}</div>
<div><strong>Status:</strong> {{.Status}}</div>
<div><strong>Generated:</strong> {{.Generated.Format "2006-01-02 15:04:05"}}</div>
<div><strong>Alive:</strong> {{.AliveCount}} &nbsp; <strong>Dead:</strong> {{.DeadCount}}</div>
</div>

{{range .AliveHosts}}
<h2 class="alive">{{.IP}}{{if .OS}} — {{.OS}}{{end}}</h2>
{{if .OpenPorts}}
<table>
<thead><tr><th>Port</th><th>Service</th><th>Banner</th></tr></thead>
<tbody>
{{range .OpenPorts}}
<tr><td>{{.Port}}</td><td>{{.Service}}</td><td><code>{{.Banner}}</code></td></tr>
{{end}}
</tbody>
</table>
{{end}}
{{if .VulnFindings}}
<table>
<thead><tr><th>Severity</th><th>Title</th><th>CVE</th><th>Evidence</th></tr></thead>
<tbody>
{{range .VulnFindings}}
<tr><td class="sev-{{.Severity}}">{{.Severity}}</td><td>{{.Title}}</td><td>{{.CVE}}</td><td><code>{{.Evidence}}</code></td></tr>
{{end}}
</tbody>
</table>
{{end}}
{{end}}

{{if .DeadHosts}}
<h2>Unresponsive hosts</h2>
<ul>
{{range .DeadHosts}}<li class="dead">{{.IP}}</li>{{end}}
</ul>
{{end}}

<p><em>Generated by Penego at {{.ExportedAt.Format "2006-01-02 15:04:05"}}</em></p>
</body>
</html>`

type reportData struct {
	ID           uint
	ScanType     string
	Target       string
	PortsScanned string
	Status       string
	Generated    time.Time
	AliveCount   int
	DeadCount    int
	AliveHosts   []models.HostResult
	DeadHosts    []models.HostResult
	ExportedAt   time.Time
}

func RenderHTMLReport(s models.ScanReport) ([]byte, error) {
	alive := s.TrueTargets()
	dead := s.FalseTargets()
	data := reportData{
		ID:           s.ID,
		ScanType:     s.ScanType,
		Target:       s.Target,
		PortsScanned: s.PortsScanned,
		Status:       s.Status,
		Generated:    s.Generated,
		AliveCount:   len(alive),
		DeadCount:    len(dead),
		AliveHosts:   alive,
		DeadHosts:    dead,
		ExportedAt:   time.Now(),
	}
	tmpl, err := template.New("report").Parse(reportHTML)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func ReportFilename(s models.ScanReport) string {
	return fmt.Sprintf("penego-scan-%d.html", s.ID)
}
