package services

import (
	"bytes"
	"fmt"
	"html/template"
	"time"

	"penego/models"
)

const engagementReportHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Penego Engagement Report — {{.Name}}</title>
<style>
body{font-family:Georgia,serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;line-height:1.45}
h1,h2{border-bottom:2px solid #333;padding-bottom:.3rem}
.meta{color:#555;margin-bottom:1.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:.95rem}
th,td{border:1px solid #ccc;padding:.4rem .6rem;text-align:left}
th{background:#f0f0f0}
.sev-critical,.sev-high{color:#a00;font-weight:bold}
.sev-medium{color:#a60}
.sev-low,.sev-info{color:#06a}
@media print{body{margin:0}}
</style>
</head>
<body>
<h1>Penego Assessment Report</h1>
<div class="meta">
<div><strong>Engagement:</strong> {{.Name}}</div>
<div><strong>Status:</strong> {{.Status}}</div>
<div><strong>Scope:</strong> {{.Scope}}</div>
<div><strong>Generated:</strong> {{.ExportedAt.Format "2006-01-02 15:04:05"}}</div>
<div><strong>Assets:</strong> {{.AssetCount}} &nbsp; <strong>Open findings:</strong> {{.OpenFindings}}</div>
</div>
{{if .Description}}<p>{{.Description}}</p>{{end}}

<h2>Executive summary</h2>
<p>This assessment-focused report summarizes hosts discovered within the engagement scope,
service enumeration highlights, and vulnerability/auth findings. No exploitation was performed.</p>
<ul>
<li>Critical: {{.CountCritical}}</li>
<li>High: {{.CountHigh}}</li>
<li>Medium: {{.CountMedium}}</li>
<li>Low / Info: {{.CountLow}}</li>
</ul>

<h2>Asset inventory</h2>
<table>
<thead><tr><th>IP</th><th>Hostname</th><th>OS</th><th>Ports</th><th>TLS CN</th><th>HTTP Title</th></tr></thead>
<tbody>
{{range .Assets}}
<tr>
<td>{{.IP}}</td><td>{{.Hostname}}</td><td>{{.OS}}</td><td>{{.OpenPorts}}</td><td>{{.TLSCN}}</td><td>{{.HTTPTitle}}</td>
</tr>
{{end}}
</tbody>
</table>

<h2>Findings</h2>
<table>
<thead><tr><th>Severity</th><th>Status</th><th>Title</th><th>CVE</th><th>Port</th><th>Remediation</th></tr></thead>
<tbody>
{{range .Findings}}
<tr>
<td class="sev-{{.Severity}}">{{.Severity}}</td>
<td>{{.Status}}</td>
<td>{{.Title}}</td>
<td>{{.CVE}}</td>
<td>{{.Port}}</td>
<td>{{.Remediation}}</td>
</tr>
{{end}}
</tbody>
</table>

<h2>Scan timeline</h2>
<table>
<thead><tr><th>ID</th><th>Type</th><th>Target</th><th>Status</th><th>When</th></tr></thead>
<tbody>
{{range .Scans}}
<tr><td>{{.ID}}</td><td>{{.ScanType}}</td><td>{{.Target}}</td><td>{{.Status}}</td><td>{{.Generated.Format "2006-01-02 15:04"}}</td></tr>
{{end}}
</tbody>
</table>

<p><em>Generated by Penego assessment toolkit — authorized testing only.</em></p>
</body>
</html>`

type engagementReportData struct {
	Name          string
	Status        string
	Scope         string
	Description   string
	ExportedAt    time.Time
	AssetCount    int
	OpenFindings  int
	CountCritical int
	CountHigh     int
	CountMedium   int
	CountLow      int
	Assets        []models.Asset
	Findings      []models.Finding
	Scans         []models.ScanReport
}

func RenderEngagementReport(e models.Engagement, assets []models.Asset, findings []models.Finding, scans []models.ScanReport) ([]byte, error) {
	data := engagementReportData{
		Name:        e.Name,
		Status:      e.Status,
		Scope:       e.ScopeCIDRs,
		Description: e.Description,
		ExportedAt:  time.Now(),
		AssetCount:  len(assets),
		Assets:      assets,
		Findings:    findings,
		Scans:       scans,
	}
	for _, f := range findings {
		if f.Status == models.FindingOpen {
			data.OpenFindings++
		}
		switch f.Severity {
		case models.SeverityCritical:
			data.CountCritical++
		case models.SeverityHigh:
			data.CountHigh++
		case models.SeverityMedium:
			data.CountMedium++
		default:
			data.CountLow++
		}
	}
	tmpl, err := template.New("engreport").Parse(engagementReportHTML)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func EngagementReportFilename(e models.Engagement) string {
	return fmt.Sprintf("penego-engagement-%d.html", e.ID)
}
